image: ubuntu:18.04

stages:
    - cluster
    - metrics
    - hpa
    - ca

#prepare container image
before_script:
        - apt-get update
        - apt-get install curl -y
        - chmod +x kops/kubectl.sh
        - chmod +x kops/ins-kops.sh
        - ./kops/ins-kops.sh
        - ./kops/kubectl.sh
        - kops export kubecfg ${NAME}

####################
## Update Cluster ##
####################

cluster:
    stage: cluster
    script:
        #deploy K8s cluster
        - chmod +x deploy.sh
        - sh deploy.sh

############################
## install metrics server ##
############################

metrics:
    stage: metrics
    script:
    - kubectl apply -f ./metrics/