image: ubuntu:18.04

stages:
    - cluster
    - metrics
    - hpa
    - ca

####################
## Update Cluster ##
####################

cluster:
    stage: cluster
    script:
        #deploy K8s cluster
        - sh deploy.sh

############################
## install metrics server ##
############################

metrics:
    stage: metrics
    script:
    - kubectl apply -f ./metrics/