stages:
    - cluster
    - metrics
    - hpa
    - ca

####################
## Update Cluster ##
####################

cluster:
    stage: cluster
    script:
        - ./deploy.sh

metrics:
    stage: metrics
    script:
        - echo "Testing"
        - test -f "build/info.txt"