image: ubuntu:18.04

stages:
    - cluster
    - metrics
    - hpa
    - ca
 
####################
## Update Cluster ##
####################

cluster:
    stage: cluster
    script:
        #prepare container image
        - apt-get update
        - apt-get install curl -y
        - chmod +x kops/kubectl.sh
        - chmod +x kops/ins-kops.sh
        - ./kops/ins-kops.sh
        - ./kops/kubectl.sh
        #deploy K8s cluster
        - chmod +x deploy.sh
        - sh deploy.sh

############################
## install metrics server ##
############################

metrics:
    stage: metrics
    script:
    #install kubectl
    - chmod +x kops/kubectl.sh
    - ./kops/kubectl.sh
    - kubectl apply -f ./metrics/