image: ubuntu:18.04

stages:
    - runnercontainer
    - cluster
    - metrics
    - hpa
    - ca

########################
## setup runner image ##
########################

runnercontainer:
    stage: runnercontainer
    script:
        - apt-get update
        - apt-get install curl -y
        - chmod +x kops/ins-kops.sh
        - ./kops/ins-kops.sh
        
####################
## Update Cluster ##
####################

cluster:
    stage: cluster
    script:
        - chmod +x deploy.sh
        - sh deploy.sh

metrics:
    stage: metrics
    script:
        - echo "Testing"
        - test -f "build/info.txt"