image: ubuntu:18.04

before_script:
        - apt-get update
        - apt-get install curl -y
        - ./kops/ins-kops.sh
        - ./kops/kubectl.sh

stages:
    - cluster

####################
## Update Cluster ##
####################

cluster:
    stage: cluster
    script:
        #deploy K8s cluster
        - sh deploy.sh